### PR TITLE
update index

### PR DESCRIPTION
**Pull request by paralltheshape**
add logo. okay

### CODE REVIEW

**Comment by KoolKidz112** [comment]
what

**Comment by KoolKidz112** [comment]
looks good thanks

**Comment by paralltheshape** [comment]
nigga u stupid??

**Comment by KoolKidz112** [comment]
shut up

**Comment by paralltheshape** [comment]
jew mad
bro?

**Comment by KoolKidz112** [comment]
jew mad bro that this organization > pubie2

**Comment by paralltheshape** [comment]
im going to hack ur github acc

**Comment by KoolKidz112** [comment]
noo

**Pull request merged**
